### ISSUE TITLE
Cant send mail on thunderbird 52.0

### ISSUE THREAD

**Issue by trickre** [Meatian/confirm-address#29]
After updating thunderbird 52.0 confirm-address Add-on stop sending email.

(Turn off this Add-on, can send mail)

**Comment by thortex** [comment]
Did you try out the following newest version?
https://github.com/Meatian/confirm-address/blob/master/release/confirm-address_1.2.9a.xpi
https://github.com/Meatian/confirm-address/blob/master/release/confirm-address_1.2.9.3a.xpi

#29 has fixed in https://github.com/Meatian/confirm-address/commit/26a36d1cc7d1b4cfb25b8c00badb83f6ab359567.

**Comment by LauraAmorim** [comment]
confirm-address_1.2.9.3a.xpi is working with  thunderbird 52.0.1. I must choose the option " Not display the message  for my domain emails", if not, no error messages but nothing happens when click 'send' mail.

**Comment by LinuxOnTheDesktop** [comment]
Same problem on Thunderbird 60.5.0 on Windows 8.1. I will try the 1.2.9.3a xpi, I suppose . .

**Comment by LinuxOnTheDesktop** [comment]
No, still doesn't work, perhaps because I have the 'not display . .' option mentioned by @LauraAmorim disabled; I tried to turn it on, but the 'OK' button on the options window did not work. Dear me.

**Comment by Meatian** [comment]
Which version of Confirm-Address do you use?  I recommend version 1.3.2 for
Thunderbird 60.*.
https://addons.thunderbird.net/en-US/thunderbird/addon/confirm-address-5582/
